services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
      platforms:
        - linux/amd64
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_URL=${GROQ_API_URL}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MODEL_NAME=${MODEL_NAME}
    volumes:
      - ./backend:/app/backend
    networks:
      - rag-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      platforms:
        - linux/amd64
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge 